### ISSUE TITLE
Store the todo list on the server

### ISSUE THREAD

**Issue by cm86** [themaxsandelin/todo#2]
Hello i really like your feature, is it possible to store the content of the todo list on the server?

- i open the list with my mac
- entered something, closed it here
- opened it on my iPhone it was empty

-same like opening first as desktop-app on the iPhone and then opened in safari on the iPhone.

Mit freundlichen Grüßen
Chris

**Comment by themaxsandelin** [comment]
Thanks for the suggestion! As this is not an issue in itself I will close this but I will keep this suggestion in mind for future videos 👍
